spring:
  messages:
    basename: i18n/message
    fallback-to-system-locale: false

application:
#  language: ru-RU
  language: en-EN
dao:
  questionFile: /questions.csv
passedTest:
  rightAnswers: 4