spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 0
      database: SpringBatchExampleDB

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.migration.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

#debug: true
